### ISSUE TITLE
Does not work with Grails 3.3.x due to FilterRegistrationBean has been moved in Spring Boot

### ISSUE THREAD

**Issue by andersaaberg** [rpalcolea/grails-xss-sanitizer#1]
Grails 3.3.x upgrades Spring Boot to 1.5 which moves the FilterRegistrationBean to a different package and this makes the grails-xss-sanitizer plugin fail with ClassNotFound:
```java.lang.NoClassDefFoundError: org/springframework/boot/context/embedded/FilterRegistrationBean
	at grails.plugin.xss.sanitizer.XssSanitizerGrailsPlugin.doWithSpring_closure1(XssSanitizerGrailsPlugin.groovy:38)```

See http://docs.grails.org/latest/guide/upgrading.html
> Spring Boot 1.5.x removes a number of deprecated classes, notably all of the classes within the org.springframework.boot.context.embedded package.
> 
> If your application is referencing any of the classes within this package you will need to alter your imports to use org.springframework.boot.web.servlet instead.

The solution is to change the referenced package in XssSanitizerGrailsPlugin and change the grailsVersion to 3.3.x.

**Comment by pulikkot** [comment]
Any chance to get the upgraded plugin in Grails 3 Plugin list?

Thanks a lot
pulikkot
